### ISSUE TITLE
Issues when remote broker does not have a hostname matching a FQDN

### ISSUE THREAD

**Issue by butlermatt** [pulyaevskiy/dart-kafka#6]
I'm trying to connect to a remote kafka server, lets call it: `server1.mydomain.com` (on port 9092).

For reasons outside of my control, that server's hostname (when running the `hostname` command) shows as something very different like `My-TestServer`.

When running the dart kafka client locally I get a fatal error (that kills the app regardless of try/catch blocks)

```
Consumer: Running worker on host My-TestServer:9092
Consumer: Running worker on host My-TestServer:9092
Consumer: Running worker on host My-TestServer:9092
Unhandled exception:
SocketException: Failed host lookup: 'My-TestServer' (OS Error: nodename nor servname provided, or not known, errno = 8)
#0      _NativeSocket.lookup.<anonymous closure> (dart:io-patch/socket_patch.dart:330)
#1      _RootZone.runUnary (dart:async/zone.dart:1149)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:502)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:585)
#4      _Future._completeWithValue (dart:async/future_impl.dart:376)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:430)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#7      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

This is despite the fact that I have a the correct `server1.mydomain.com` configured in the `ContactPoint`

**Comment by pulyaevskiy** [comment]
Thanks @butlermatt !

Do you have access to broker configuration file on that server? You might need to set `advertised.host.name` parameter in broker config to match public DNS of that server (which is `server1.mydomain.com` in your example).

The client uses ContactPoints only in the beginning of the flow. It makes MetadataRequest to one of the ContactPoints which returns hostnames and ports of all the brokers in the cluster. Then this information is used to communicate with all the nodes in the cluster (instead of ContactPoints).

Seems like MetadataRequest returns local hostname of your broker and there is no way for the client to resolve it, unfortunately. If you set `advertised.host.name` in the broker config then MetadataRequest will return your value and everything should work.

Re: uncatchable error. This is probably similar to the other issue. I will look at this and submit a PR shortly.

**Comment by pulyaevskiy** [comment]
@butlermatt 

Could you double check that "uncatchable" error still persists on your side even after #4 has been merged?

I can't seem to reproduce it on my end with latest master.

**Comment by butlermatt** [comment]
Yes, that is where I encountered the error was on the separate branch for #4. That again was only when the broker was not providing correct domain/hostname back to the client. Setting the advertised.host.name and advertised.port resolved that issue.

**Comment by pulyaevskiy** [comment]
Great, closing this one than.

Thank you!
